#!/bin/bash
if [ -z "$1" ]; then
    echo "No args suplied"
    exit 1
fi

if [ "$1" -gt "10239" ]; then
    sudo sysctl -w kern.maxfiles=$1
    sudo sysctl -w kern.maxfilesperproc=$1
    ulimit -n $1 $1
else
    echo "$1 is too low (minor than 10240)"
fi
